theme: jekyll-theme-minimal

title: Colette & Eric
description: Good news, everyone! We're getting married!
authors: "Colette Alexander + Eric J. Humphrey"

menu:
  brooklyn:
    url: /pages/brooklyn
    title: "Friday, June 29th – Brooklyn, NY"
  michigan:
    url: /pages/michigan
    title: "Saturday, July 7th – Ann Arbor, MI"
  massachusetts:
    url: /pages/massachusetts
    title: "Sunday, July 22nd – Webster, MA"
  about:
    url: /pages/about
    title: "About Us"
  photos:
    url: /pages/photos
    title: "Photos"
  honeymoon:
    url: /pages/honeymoon
    title: "The Honeymoon"
  registry:
    url: /pages/registry
    title: "Registry"

exclude:
  - Gemfile
  - Gemfile.lock